#!/usr/bin/env python

from config import returnKeys
import subprocess

subprocess.run("alacritty")

keybindings = returnKeys()

for i in range(len(keybindings)):
    print(f"{i}. Keys: {keybindings[i].getKeys()} Desciption: {keybindings[i].getDesc()}")

